[browser]
gatherUsageStats = false

[server]
headless = true
port = 5000

[theme]
base = "light"

[client]
toolbarMode = "minimal"

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "debug"
